Vagrant.configure("2") do |config|
 config.vm.disk :disk, size: "30GB", primary: true
 config.vm.provision "file", source: "jewish-calendar.py", destination: "jewish-calendar.py"
 config.vm.provision "file", source: "req.txt", destination: "req.txt"
config.vm.provider "virtualbox" do |v|
 v.name = "calendar"
  end  
config.vm.network "private_network", ip: "192.168.56.1"
  config.vm.box = "centos/7"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y python3 
    pip3 install -r req.txt
    echo "      
          jewish calendar"
    sudo python3 jewish-calendar.py
    
  SHELL
end
